version: '3'
services:
  buggybank:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./database:/app/database
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1 